### ISSUE TITLE
Is this still being actively developed?

### ISSUE THREAD

**Issue by ghost** [arqadium/oco-engine#12]
Is this still being actively developed or has it been set to the back burner or abandoned?

**Comment by nicholatian** [comment]
Yes, it is still in development, as is the ÔÇô Toolchain and such. I've a roadmap that ends right before 3D feature development, and I need to publish it on [my weblog](https://nicholatian.com/) before the end of the year.

I'm going to close this issue for now though, because it's pretty off-topic for GitHub and the discussion can certainly continue on [Discord](https://discord.gg/VbJAsHX) or [Twitter](https://twitter.com/arqadium). Thanks for bringing this up, hope to see you around🙂
